# See https://github.com/krzema12/github-actions-typing
inputs:
  aws-access-key-id:
    type: string
  aws-secret-access-key:
    type: string
  aws-session-token:
    type: string
  aws-region:
    type: string
  mask-aws-account-id:
    type: string
  role-to-assume:
    type: string
  web-identity-token-file:
    type: string
  role-duration-seconds:
    type: integer
  role-session-name:
    type: string
  role-external-id:
    type: string
  role-skip-session-tagging:
    type: boolean
# Please check those outputs's description and set a proper type. 'string' is just set by default
outputs:
  aws-account-id:
    type: string
