name: Debugging
on:
  push:
    branches:
    - main
  pull_request: {}
jobs:
  check_yaml_consistency:
    runs-on: ubuntu-latest
    steps:
    - id: step-0
      name: Check out
      uses: actions/checkout@v3
    - id: step-05
      name: Execute shared script
      run: '.github/workflows/_shared.main.kts'
    - id: step-1
      name: Execute script
      run: rm '.github/workflows/build.yaml' && '.github/workflows/build.main.kts'
    - id: step-2
      name: Consistency check
      run: git diff --exit-code '.github/workflows/build.yaml'
